src/App.css, src/App.js, src/cards/cards.css, src/cards/cards.js, src/movies/movies.css, src/movies/movies.js
Add initial styling to cards
**Changes:**
- Added initial styling to cards
-  Refactored code to use props in JSX
=> Add initial styling to cards

public/index.html, src/App/App.css, src/App/App.js, src/header/header.css, src/header/header.js, src/movies/movies.js
- Add header component to app
- Add styling to header component
=> Add header component to app

src/App/App.css, src/cards/cards.css, src/cards/cards.js, src/movies/movies.js
- Add additional styling
- Round Average Ratings
=> Add additional styling and round average ratings

package-lock.json, package.json, src/App/App.css, src/App/App.js, src/cards/cards.js, src/detailPage/detailPage.css, src/detailPage/detailPage.js, src/movies/movies.js
- Get initial unstyled data to display
- Adjust styling for selected movie view
=> Feature/show movie details/br

src/App/App.js, src/cards/cards.js, src/header/header.css, src/header/header.js
- Add unstyled back button to detail page
@ben-rosner-williamsburg 
Still needs adjusting with styling.
=> Add back button to detail page

src/cards/cards.js, src/detailPage/detailPage.js
- Fixed rating by adding tomatoes to home page
- Fixed rating so that it shows one decimal point
- [ X] My PR has a clear description of all proposed changes.
- [X ] My PR denotes any/all team members who contributed to it.
- [ X] My code follows the Turing Style Guides and best practices.
- [ X] I ran the code locally and verified that there are no visible errors.
- [ X] feat: My code is clean and readable, so my teammates can easily review it.
- [X ] fix: My PR clearly describes not only the fix itself, but the reason for the fix.
- [ X] refactor: My PR clearly describes not only the refactor itself, but the reason for the refactor.
Left the styling as it is
=> Add tomato to rating and ensure that one decimal point is showing

src/App/App.js, src/apiCalls/apiCalls.js, src/movies/movies.js
- Created directory and file called apiCalls
- Moved getMovies function to apiCalls
- Created fetchData function to handle the fetched data
- 
- [ X] My PR has an appropriately descriptive and concise title.
- [X ] My PR has a clear description of all proposed changes.
- [X ] My PR denotes any/all team members who contributed to it.
- [ X] My code follows the Turing Style Guides and best practices.
- [ X] I ran the code locally and verified that there are no visible errors.
- [X ] feat: My code is clean and readable, so my teammates can easily review it.
- [] fix: My PR clearly describes not only the fix itself, but the reason for the fix.
=> Move api calls from App component to  a separate directory

src/App/App.js, src/apiCalls/apiCalls.js, src/cards/cards.js, src/detailPage/detailPage.js, src/header/header.js, src/index.js, src/movies/movies.js
- Update api calls to include single movie request
- Implement react router throughout application
=> Update api calls and implement react router

cypress.config.js, cypress/e2e/spec.cy.js, cypress/fixtures/example.json, cypress/fixtures/testData.json, cypress/support/commands.js, cypress/support/e2e.js, package-lock.json, package.json
- Install cypress
- Create spec.cy.js within cypress file
- Create testData file with some of the movie data
- Pass tests for page load and clicking on a movie
Router is not working properly to go back to the home page so I stopped here for now
=> Testing user flow from page load to clicking on a particular movie

src/App/App.js, src/BackBtn/BackBtn.js, src/detailPage/detailPage.js, src/header/header.js
- Add useNavigate hook to header component
- [Implement correct routing
@ben-rosner-williamsburg 
@zenmcmillan 
Back button still appearing when browser back button is clicked
=> Feature/react router/br

src/App/App.js, src/BackBtn/BackBtn.css, src/detailPage/detailPage.css, src/detailPage/detailPage.js, src/header/header.css, src/header/header.js
-  Move back button component to detail page
@ben-rosner-williamsburg 
This removes the need for conditional rendering
=> Move back button component to detail page

src/App/App.css, src/App/App.js, src/App/App.test.js, src/Cards/Cards.css, src/detailPage/detailPage.js, src/movies/movies.js
=> Refactor/delete unused files/br

src/App/App.js, src/Cards/Cards.css, src/detailPage/detailPage.js, src/movies/movies.js
- Change movieData prop name to singleMovie in detail page
- Change card dimensions to accommodate more text
- # Contributors
@ben-rosner-williamsburg 
Changed movieData prop name to singleMovie to be more verbose
=> Rename movieData prop

public/index.html, src/App/App.js, src/BackBtn/BackBtn.css, src/BackBtn/BackBtn.js
- Change back button to home button
=> Change back button to home button

cypress/fixtures/testData.json, src/App/App.js, src/Cards/Cards.js, src/Error/Error.css, src/Error/Error.js, src/detailPage/DetailPage.js, src/header/header.js
=> Add 400 error handling

src/App/App.css, src/Cards/Cards.css, src/detailPage/DetailPage.css
- Convert px to em in CSS
- [] I ran the code locally and verified that there are no visible errors.
The spacing between the top of the card and the poster may be a bit to thin
=> Convert px to em in css

src/App/App.css, src/App/App.js, src/Cards/Cards.css, src/Cards/Cards.js, src/Error/Error.css, src/Error/Error.js, src/HomeBtn/HomeBtn.css, src/detailPage/DetailPage.css, src/header/header.css, src/movies/movies.css, src/movies/movies.js
-Add small breakpoint for responsive design
-Change movie poster dimensions to view height and view width
=> Feature/responsive design/br

src/App/App.css, src/Cards/Cards.css, src/Error/Error.css, src/Error/Error.js, src/HomeBtn/HomeBtn.css, src/detailPage/DetailPage.css, src/detailPage/DetailPage.js, src/header/header.css, src/movies/movies.css
- Change px to responsive units
- Edit dimensions of some elements to fit better
=> Change px to responsive units

src/App/App.css, src/Cards/Cards.css, src/Error/Error.css, src/HomeBtn/HomeBtn.css, src/detailPage/DetailPage.css, src/movies/movies.css
=> Add large breakpoints

src/App/App.css, src/App/App.js, src/Cards/Cards.css, src/Error/Error.css, src/HomeBtn/HomeBtn.css, src/detailPage/DetailPage.css, src/header/header.css, src/movies/movies.css
- Change font sizes to match 100% zoom setting
=> Change font sizes to match 100% zoom setting

src/App/App.js, src/Cards/Cards.css, src/Cards/Cards.js, src/HomeBtn/HomeBtn.css, src/HomeBtn/HomeBtn.js, src/detailPage/DetailPage.css, src/detailPage/DetailPage.js, src/movies/movies.js
- Delete stray comments
- Clean up responsive design
=> Delete stray comments and clean up responsive design

src/DetailPage/DetailPage.js
Remove console log and add missing colon to popularity field
=> Remove console log and add missing colon to popularity field
